---

- name: gather eip facts by name
  ec2_eip_facts:
    aws_access_key: "{{ lookup('ENV', 'AWS_ACCESS_KEY') | default(omit) }}"
    aws_secret_key: "{{ lookup('ENV', 'AWS_SECRET_KEY') | default(omit)  }}"
    security_token: "{{ lookup('ENV', 'AWS_SECURITY_TOKEN') | default(omit) }}"
    profile: "{{ aws_vpc_nat_profile | default(omit) }}"
    region: "{{ natgw.region | default(aws_vpc_nat_default_region) }}"
    filters:
      "tag:Name": "{{ natgw.eip_name }}"
  register: _aws_eip_facts

- name: fail if no eip was found
  assert:
    that:
      - _aws_eip_facts.addresses is defined
      - _aws_eip_facts.addresses | length == 1
    msg: Not exactly one eip has been found

- name: set eip id and name
  set_fact:
    _aws_eip_id: "{{ _aws_eip_facts.addresses[0].allocation_id }}"
    _aws_eip_ip: "{{ _aws_eip_facts.addresses[0].public_ip }}"
